/** A drawing row in the shape shared by local SQLite and Cloudflare D1. */
export interface D1DrawRow {
  game_id: string;
  draw_date: string;
  draw_slot: string;
  numbers: string;
  extras: string;
  source: string;
}

const esc = (s: string) => `'${s.replace(/'/g, "''")}'`;

/**
 * Render an idempotent D1 import. The conflict guard is important: corrected
 * official results replace stale values, while unchanged history consumes no
 * writes and retains its original ingestion timestamp.
 */
export function renderD1SeedSql(rows: D1DrawRow[], rowsPerInsert = 200): string {
  const out: string[] = [
    '-- NumberIQ drawing history, generated by server/src/cli/export-d1.ts',
    '-- Idempotent: corrections are updated; unchanged rows are not rewritten.',
    '',
  ];

  for (let i = 0; i < rows.length; i += rowsPerInsert) {
    const chunk = rows.slice(i, i + rowsPerInsert);
    const values = chunk
      .map((r) => `(${esc(r.game_id)},${esc(r.draw_date)},${esc(r.draw_slot)},${esc(r.numbers)},${esc(r.extras)},${esc(r.source)})`)
      .join(',\n  ');
    out.push(
      `INSERT INTO draws (game_id, draw_date, draw_slot, numbers, extras, source) VALUES\n  ${values}\n` +
      `ON CONFLICT (game_id, draw_date, draw_slot) DO UPDATE SET\n` +
      `  numbers = excluded.numbers,\n` +
      `  extras = excluded.extras,\n` +
      `  source = excluded.source,\n` +
      `  ingested_at = strftime('%Y-%m-%d %H:%M:%f', 'now')\n` +
      `WHERE draws.numbers IS NOT excluded.numbers\n` +
      `   OR draws.extras IS NOT excluded.extras\n` +
      `   OR draws.source IS NOT excluded.source;`,
    );
  }

  return out.join('\n') + '\n';
}
